# Generated by Django 4.1 on 2022-08-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(default='no description')),
                ('image', models.ImageField(default='../images/default_book.png', upload_to='')),
            ],
        ),
    ]
