# Generated by Django 4.1 on 2022-08-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_backend', '0002_remove_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='../images/default_book.png', upload_to=''),
        ),
    ]
