# Generated by Django 4.1 on 2022-08-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_backend', '0003_remove_book_description_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='no description'),
        ),
    ]
